"""
Unified any-modality atom tokenizer.

This is the mechanism (Section 2.2 of the project plan) that makes "any type of
interaction at scale" tractable: protein, RNA, DNA, ligand, ion, and PTM atoms all
become the same `AtomToken` type, consumed by one model instead of per-modality
models (contrast with RFdiffusion3, which bolts on a separate model for nucleic
acids). Polymer residues (protein/RNA/DNA) get a fixed, padded slot layout drawn
from `AtomVocab.RESIDUE_ATOMS`, with missing/inapplicable atoms marked `is_virtual`.
Non-polymer residues (ligand/ion/PTM) are tokenized atom-by-atom with no padding,
since they have no canonical slot layout.
"""
module Tokenizer

using ..AtomVocab

export AtomToken, ParsedResidue, tokenize_residue, tokenize_structure

"""
    AtomToken

One atom's worth of model input. `coord` is `nothing` when the atom's position is
unknown/unobserved (e.g. missing density in a crystal structure, or an atom to be
generated by the model) — tokenization is geometry-agnostic, coordinates are
attached or diffused separately.

Fields:
- `element`: element symbol, e.g. `:C`, `:N`, `:Zn`.
- `modality`: which `AtomVocab.Modality` this atom belongs to.
- `chain_id`: chain/entity identifier as given in the source structure.
- `res_index`: 1-based residue index within its chain.
- `res_name`: residue/component name (e.g. `"ALA"`, `"A"`, `"DG"`, `"HEM"`, `"ZN"`).
- `atom_name`: atom name within the residue (e.g. `"CA"`, `"OD1"`).
- `is_virtual`: true for padding slots in fixed-layout polymer residues that have
  no corresponding real atom (e.g. glycine's absent sidechain slots).
- `coord`: `(x, y, z)` in angstroms, or `nothing` if unknown.
"""
struct AtomToken
    element::Symbol
    modality::Modality
    chain_id::String
    res_index::Int
    res_name::String
    atom_name::String
    is_virtual::Bool
    coord::Union{Nothing,NTuple{3,Float64}}
end

"""
    ParsedResidue

Intermediate representation a structure-file parser (PDB/mmCIF/CCD; not yet
implemented — see `Data` module) is expected to produce, decoupling the tokenizer
from any particular file format.

- `present_atoms`: maps atom name -> coordinate for atoms actually observed.
  Atoms in a polymer residue's canonical slot layout that are absent from this
  dict become virtual padding tokens; for ligand/ion/PTM residues every entry
  becomes one real atom token (`element` is inferred from the atom name's
  leading element symbol unless `elements` overrides it).
"""
struct ParsedResidue
    chain_id::String
    res_index::Int
    res_name::String
    modality::Modality
    present_atoms::Dict{String,NTuple{3,Float64}}
    elements::Dict{String,Symbol}  # atom_name -> element override, mainly for non-polymer residues
end

ParsedResidue(chain_id, res_index, res_name, modality, present_atoms) =
    ParsedResidue(chain_id, res_index, res_name, modality, present_atoms, Dict{String,Symbol}())

function infer_element(atom_name::AbstractString)::Symbol
    # Standard PDB atom names lead with the element symbol (e.g. "CA" -> C, "NZ" -> N,
    # "OD1" -> O); this is a heuristic sufficient for the standard polymer vocabulary
    # and should be overridden via `ParsedResidue.elements` for anything else (metals,
    # halogens, etc.).
    isempty(atom_name) && throw(ArgumentError("empty atom name"))
    Symbol(uppercase(atom_name[1:1]))
end

"""
    tokenize_residue(res::ParsedResidue) -> Vector{AtomToken}

Tokenize a single residue. Polymer modalities (`PROTEIN`, `RNA`, `DNA`) produce a
fixed-length token vector following `AtomVocab.atom_slots(res.res_name)`, padded
with virtual tokens for absent atoms. Non-polymer modalities (`LIGAND`, `ION`,
`PTM`) produce one token per entry in `res.present_atoms`, in insertion order.
"""
function tokenize_residue(res::ParsedResidue)::Vector{AtomToken}
    if res.modality in (PROTEIN, RNA, DNA)
        slots = atom_slots(res.res_name)
        return [
            AtomToken(
                get(res.elements, name, infer_element(name)),
                res.modality,
                res.chain_id,
                res.res_index,
                res.res_name,
                name,
                !haskey(res.present_atoms, name),
                get(res.present_atoms, name, nothing),
            )
            for name in slots
        ]
    else
        return [
            AtomToken(
                get(res.elements, name, infer_element(name)),
                res.modality,
                res.chain_id,
                res.res_index,
                res.res_name,
                name,
                false,
                coord,
            )
            for (name, coord) in res.present_atoms
        ]
    end
end

"""
    tokenize_structure(residues) -> Vector{AtomToken}

Tokenize a full multi-chain, multi-modality complex (e.g. a protein-RNA-ligand-ion
assembly) into one flat token sequence, in the order `residues` is given.
"""
function tokenize_structure(residues::AbstractVector{ParsedResidue})::Vector{AtomToken}
    tokens = AtomToken[]
    for res in residues
        append!(tokens, tokenize_residue(res))
    end
    tokens
end

end # module
